<a href="https://colab.research.google.com/github/GreeshmaHarids/Greeshma_Meta_Scifor_Technology/blob/main/Machine_Learning/Revised_Basic_SVC_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Support Vector Classifier Implementation

In [27]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns

In [33]:
data=pd.read_csv('/content/UniversalBank.csv')

In [34]:
data.head()

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [35]:
data.isna().sum()

ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [36]:
data.dtypes

ID                      int64
Age                     int64
Experience              int64
Income                  int64
ZIP Code                int64
Family                  int64
CCAvg                 float64
Education               int64
Mortgage                int64
Personal Loan           int64
Securities Account      int64
CD Account              int64
Online                  int64
CreditCard              int64
dtype: object

In [38]:
data.drop(["ID", "ZIP Code", "Family","CCAvg","Education","Mortgage","Securities Account","CD Account"],axis=1,inplace=True)


In [39]:
X=data.drop('Personal Loan',axis=1)
y=data['Personal Loan']

In [40]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=10)

In [41]:
from sklearn.svm import SVC

In [42]:
svc=SVC(kernel='linear')

In [43]:
svc.fit(X_train,y_train)

SVC(kernel='linear')

In [44]:
svc.coef_

array([[ 1.10752726e-04, -1.11570561e-04,  3.49352922e-06,
         8.70174819e-05, -3.66261918e-06]])

In [45]:
## Prediction
y_pred=svc.predict(X_test)

In [46]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [47]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [48]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.91      1.00      0.95      1134
           1       0.00      0.00      0.00       116

    accuracy                           0.91      1250
   macro avg       0.45      0.50      0.48      1250
weighted avg       0.82      0.91      0.86      1250

[[1134    0]
 [ 116    0]]
0.9072


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


## Hyperparametere Tuning With SVC

In [55]:
from sklearn.model_selection import GridSearchCV

# defining parameter range
param_grid = {'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel':['linear']
              }

In [56]:
grid=GridSearchCV(SVC(),param_grid=param_grid,refit=True,cv=5,verbose=3)

In [57]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits
[CV 1/5] END ............gamma=1, kernel=linear;, score=0.904 total time=   2.4s
[CV 2/5] END ............gamma=1, kernel=linear;, score=0.903 total time=   2.4s
[CV 3/5] END ............gamma=1, kernel=linear;, score=0.903 total time=   2.6s
[CV 4/5] END ............gamma=1, kernel=linear;, score=0.903 total time=   4.4s
[CV 5/5] END ............gamma=1, kernel=linear;, score=0.903 total time=   2.3s
[CV 1/5] END ..........gamma=0.1, kernel=linear;, score=0.904 total time=   2.4s
[CV 2/5] END ..........gamma=0.1, kernel=linear;, score=0.903 total time=   2.4s
[CV 3/5] END ..........gamma=0.1, kernel=linear;, score=0.903 total time=   2.7s
[CV 4/5] END ..........gamma=0.1, kernel=linear;, score=0.903 total time=   4.4s
[CV 5/5] END ..........gamma=0.1, kernel=linear;, score=0.903 total time=   2.3s
[CV 1/5] END .........gamma=0.01, kernel=linear;, score=0.904 total time=   2.4s
[CV 2/5] END .........gamma=0.01, kernel=linear;,

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['linear']},
             verbose=3)

In [58]:
grid.best_params_

{'gamma': 1, 'kernel': 'linear'}

In [59]:
## Prediction
y_pred4=grid.predict(X_test)
print(classification_report(y_test,y_pred4))
print(confusion_matrix(y_test,y_pred4))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.91      1.00      0.95      1134
           1       0.00      0.00      0.00       116

    accuracy                           0.91      1250
   macro avg       0.45      0.50      0.48      1250
weighted avg       0.82      0.91      0.86      1250

[[1134    0]
 [ 116    0]]
0.9072


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
